[package]
name = "spacetraders_pathfinding_rs"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "main"

[dependencies]
pathfinding = "4.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
