[package]
name = "spacetraders_pathfinding_rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pathfinding = "4.3.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
